import 'listing_model.dart';
import 'user_model.dart';
import 'notification_model.dart';

class MockData {
  static final List<ListingModel> listings = [
    // BOOST İLANLARI (12 adet)
    ListingModel(
      id: 'b1',
      title: 'BMW 5 Serisi 520d M Sport',
      brand: 'BMW',
      series: '5 Serisi',
      model: '520d',
      year: 2022,
      mileage: 28000,
      priceInTL: 2850000,
      fuelType: 'Dizel',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Siyah',
      engineSize: '2.0',
      horsepower: 190,
      location: 'Lefkoşa',
      description: 'M Sport paketi, sunroof, deri koltuk, HUD, Harman Kardon ses sistemi. Tek elden, hasarsız araç.',
      imageUrls: [
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: true,
      viewCount: 1247,
      sellerId: 'u1',
      sellerName: 'Mehmet Yılmaz',
      sellerPhone: '+90 555 123 4567',
      sellerWhatsApp: '+90 555 123 4567',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 5)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=1',
      isSellerFounderMember: true,
    ),
    ListingModel(
      id: 'b2',
      title: 'Mercedes-Benz C 200 AMG Line',
      brand: 'Mercedes-Benz',
      series: 'C Serisi',
      model: 'C 200',
      year: 2021,
      mileage: 45000,
      priceInTL: 2450000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Gümüş',
      engineSize: '1.5',
      horsepower: 204,
      location: 'Girne',
      description: 'AMG Line paketi, panoramik sunroof, MBUX, 360 derece kamera. Harika bir araç.',
      imageUrls: [
        'https://images.unsplash.com/photo-1617469767053-8f1434a3cac7?w=800',
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 892,
      sellerId: 'u2',
      sellerName: 'Ali Kaya',
      sellerPhone: '+90 533 987 6543',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 4)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=2',
      isSellerFounderMember: true,
    ),
    ListingModel(
      id: 'b3',
      title: 'Audi A4 2.0 TDI S-Line',
      brand: 'Audi',
      series: 'A4',
      model: '2.0 TDI',
      year: 2020,
      mileage: 62000,
      priceInTL: 1950000,
      fuelType: 'Dizel',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Beyaz',
      engineSize: '2.0',
      horsepower: 150,
      location: 'Mağusa',
      description: 'S-Line, virtual cockpit, matrix LED, B&O ses sistemi. Temiz ve bakımlı.',
      imageUrls: [
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 654,
      sellerId: 'u3',
      sellerName: 'Fatma Demir',
      sellerPhone: '+90 542 111 2233',
      sellerWhatsApp: '+90 542 111 2233',
      createdAt: DateTime.now().subtract(const Duration(hours: 18)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 6)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=5',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'b4',
      title: 'Volkswagen Passat 2.0 TDI',
      brand: 'Volkswagen',
      series: 'Passat',
      model: '2.0 TDI',
      year: 2023,
      mileage: 12000,
      priceInTL: 1750000,
      fuelType: 'Dizel',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Lacivert',
      engineSize: '2.0',
      horsepower: 150,
      location: 'Lefkoşa',
      description: 'Yeni nesil Passat, dijital kokpit, adaptif cruise, lane assist. Az km, sıfır gibi.',
      imageUrls: [
        'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: true,
      viewCount: 423,
      sellerId: 'u4',
      sellerName: 'Hasan Öztürk',
      sellerPhone: '+90 532 444 5566',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 7)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=7',
      isSellerFounderMember: true,
    ),
    ListingModel(
      id: 'b5',
      title: 'Toyota Camry 2.5 Hybrid',
      brand: 'Toyota',
      series: 'Camry',
      model: '2.5 Hybrid',
      year: 2022,
      mileage: 34000,
      priceInTL: 1650000,
      fuelType: 'Hibrit',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Gri',
      engineSize: '2.5',
      horsepower: 218,
      location: 'Girne',
      description: 'Tam hibrit sistem, düşük yakıt tüketimi, geniş iç mekan. Uzun yol konforunun doruk noktası.',
      imageUrls: [
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 312,
      sellerId: 'u5',
      sellerName: 'Zeynep Arslan',
      sellerPhone: '+90 545 777 8899',
      sellerWhatsApp: '+90 545 777 8899',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 2)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=9',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'b6',
      title: 'Porsche Macan S',
      brand: 'Porsche',
      series: 'Macan',
      model: 'S',
      year: 2021,
      mileage: 38000,
      priceInTL: 4200000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Kırmızı',
      engineSize: '3.0',
      horsepower: 380,
      location: 'Lefkoşa',
      description: 'Sport Chrono paketi, PASM, BOSE ses, 360 kamera. Türkiye plakalı, kusursuz araç.',
      imageUrls: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: true,
      viewCount: 2134,
      sellerId: 'u6',
      sellerName: 'Can Yıldız',
      sellerPhone: '+90 536 222 3344',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 3)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=11',
      isSellerFounderMember: true,
    ),
    ListingModel(
      id: 'b7',
      title: 'Honda CR-V 1.5 VTEC Turbo',
      brand: 'Honda',
      series: 'CR-V',
      model: '1.5 VTEC',
      year: 2021,
      mileage: 51000,
      priceInTL: 1380000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Beyaz',
      engineSize: '1.5',
      horsepower: 193,
      location: 'Mağusa',
      description: 'Honda Sensing güvenlik paketi, elektrikli bagaj, Apple CarPlay. Bakımlı araç.',
      imageUrls: [
        'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 287,
      sellerId: 'u7',
      sellerName: 'Selim Koç',
      sellerPhone: '+90 538 666 7788',
      sellerWhatsApp: '+90 538 666 7788',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 3)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=13',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'b8',
      title: 'Ford Mustang GT 5.0 V8',
      brand: 'Ford',
      series: 'Mustang',
      model: 'GT 5.0',
      year: 2020,
      mileage: 22000,
      priceInTL: 3100000,
      fuelType: 'Benzin',
      transmission: 'Manuel',
      bodyType: 'Coupe',
      color: 'Mavi',
      engineSize: '5.0',
      horsepower: 450,
      location: 'Girne',
      description: 'V8 güç, iconic tasarım, aktif egzoz, Recaro koltuk. Sürüş tutkunları için.',
      imageUrls: [
        'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
        'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 1876,
      sellerId: 'u8',
      sellerName: 'Burak Şahin',
      sellerPhone: '+90 544 333 4455',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 2)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=15',
      isSellerFounderMember: true,
    ),
    ListingModel(
      id: 'b9',
      title: 'Hyundai Tucson 1.6 T-GDI',
      brand: 'Hyundai',
      series: 'Tucson',
      model: '1.6 T-GDI',
      year: 2023,
      mileage: 8000,
      priceInTL: 1420000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Kahverengi',
      engineSize: '1.6',
      horsepower: 180,
      location: 'Lefkoşa',
      description: 'N Line, ısıtmalı koltuk, wireless CarPlay, Smart Sense. Sıfırdan farksız.',
      imageUrls: [
        'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: true,
      viewCount: 543,
      sellerId: 'u9',
      sellerName: 'Leyla Çetin',
      sellerPhone: '+90 547 888 9900',
      sellerWhatsApp: '+90 547 888 9900',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 6)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=20',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'b10',
      title: 'Land Rover Discovery Sport',
      brand: 'Land Rover',
      series: 'Discovery',
      model: 'Sport D180',
      year: 2021,
      mileage: 47000,
      priceInTL: 2750000,
      fuelType: 'Dizel',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Siyah',
      engineSize: '2.0',
      horsepower: 180,
      location: 'Mağusa',
      description: 'HSE trim, Meridian ses, panoramik tavan, Terrain Response 2. Off-road kaçamakları için ideal.',
      imageUrls: [
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 789,
      sellerId: 'u10',
      sellerName: 'Tarık Bulut',
      sellerPhone: '+90 535 555 6677',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 5)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=22',
      isSellerFounderMember: true,
    ),
    ListingModel(
      id: 'b11',
      title: 'Kia Sportage 1.6 T-GDI GT',
      brand: 'Kia',
      series: 'Sportage',
      model: '1.6 T-GDI GT',
      year: 2022,
      mileage: 25000,
      priceInTL: 1290000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Yeşil',
      engineSize: '1.6',
      horsepower: 265,
      location: 'Girne',
      description: 'GT Line, Meridian ses, ventilasyonlu koltuk, head-up display. Aileler için mükemmel.',
      imageUrls: [
        'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 334,
      sellerId: 'u11',
      sellerName: 'Murat Erdoğan',
      sellerPhone: '+90 543 111 2222',
      sellerWhatsApp: '+90 543 111 2222',
      createdAt: DateTime.now().subtract(const Duration(hours: 9)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 4)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=24',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'b12',
      title: 'Tesla Model 3 Long Range',
      brand: 'Tesla',
      series: 'Model 3',
      model: 'Long Range',
      year: 2022,
      mileage: 33000,
      priceInTL: 2200000,
      fuelType: 'Elektrik',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Beyaz',
      engineSize: 'Elektrik',
      horsepower: 366,
      location: 'Lefkoşa',
      description: 'Çift motor, 560 km menzil, Full Self-Driving. Kıbrıs\'ta nadir bulunan Tesla.',
      imageUrls: [
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
        'https://images.unsplash.com/photo-1554744512-d6c603f27c54?w=800',
      ],
      type: ListingType.boost,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: true,
      viewCount: 2567,
      sellerId: 'u12',
      sellerName: 'Deniz Aydın',
      sellerPhone: '+90 537 444 5555',
      createdAt: DateTime.now().subtract(const Duration(hours: 15)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 1)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=26',
      isSellerFounderMember: true,
    ),

    // ACİL İLANLAR
    ListingModel(
      id: 'e1',
      title: 'Renault Clio 1.0 TCe - ACİL',
      brand: 'Renault',
      series: 'Clio',
      model: '1.0 TCe',
      year: 2019,
      mileage: 78000,
      priceInTL: 580000,
      fuelType: 'Benzin',
      transmission: 'Manuel',
      bodyType: 'Hatchback',
      color: 'Kırmızı',
      engineSize: '1.0',
      horsepower: 100,
      location: 'Girne',
      description: 'Yurt dışına çıkış nedeniyle hızlı satılık. Bakımları yapılmış, hasarsız araç.',
      imageUrls: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      ],
      type: ListingType.emergency,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 445,
      sellerId: 'u13',
      sellerName: 'Emre Toprak',
      sellerPhone: '+90 546 222 3333',
      sellerWhatsApp: '+90 546 222 3333',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 3)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=30',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'e2',
      title: 'Opel Corsa 1.2 - ACİL SATILIK',
      brand: 'Opel',
      series: 'Corsa',
      model: '1.2',
      year: 2018,
      mileage: 95000,
      priceInTL: 420000,
      fuelType: 'Benzin',
      transmission: 'Manuel',
      bodyType: 'Hatchback',
      color: 'Gri',
      engineSize: '1.2',
      horsepower: 70,
      location: 'Lefkoşa',
      description: 'Bütçe sıkıntısı nedeniyle satıyorum. Aracın tüm bakımları yapılmış. Fiyat konuşulur.',
      imageUrls: [
        'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
      ],
      type: ListingType.emergency,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 234,
      sellerId: 'u14',
      sellerName: 'Pınar Kılıç',
      sellerPhone: '+90 548 555 6666',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 2)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=32',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'e3',
      title: 'Dacia Sandero 1.6 - ACİL',
      brand: 'Dacia',
      series: 'Sandero',
      model: '1.6',
      year: 2020,
      mileage: 55000,
      priceInTL: 490000,
      fuelType: 'Benzin',
      transmission: 'Manuel',
      bodyType: 'Hatchback',
      color: 'Beyaz',
      engineSize: '1.6',
      horsepower: 90,
      location: 'Mağusa',
      description: 'Ailem büyüdüğü için daha büyük araç alacağız, acil satılık. Gayet bakımlı.',
      imageUrls: [
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
      ],
      type: ListingType.emergency,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: true,
      viewCount: 321,
      sellerId: 'u15',
      sellerName: 'Kemal Doğan',
      sellerPhone: '+90 534 777 8888',
      sellerWhatsApp: '+90 534 777 8888',
      createdAt: DateTime.now().subtract(const Duration(hours: 14)),
      boostExpiresAt: DateTime.now().add(const Duration(days: 1)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=35',
      isSellerFounderMember: false,
    ),

    // NORMAL İLANLAR
    ListingModel(
      id: 'n1',
      title: 'Toyota Corolla 1.8 Hybrid',
      brand: 'Toyota',
      series: 'Corolla',
      model: '1.8 Hybrid',
      year: 2021,
      mileage: 42000,
      priceInTL: 980000,
      fuelType: 'Hibrit',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Gümüş',
      engineSize: '1.8',
      horsepower: 122,
      location: 'Lefkoşa',
      description: 'Yakıt dostu hibrit motor. Şehir içi sürüşlerde benzin tüketimi minimumda. Çok temiz araç.',
      imageUrls: [
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 156,
      sellerId: 'u16',
      sellerName: 'Selin Öz',
      sellerPhone: '+90 549 000 1111',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=40',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'n2',
      title: 'Nissan Qashqai 1.3 DIG-T',
      brand: 'Nissan',
      series: 'Qashqai',
      model: '1.3 DIG-T',
      year: 2020,
      mileage: 68000,
      priceInTL: 1150000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Kahverengi',
      engineSize: '1.3',
      horsepower: 140,
      location: 'Girne',
      description: 'Tekna+ trim seviyesi, ProPilot sürüş asistanı, 360 kamera, Bose ses. Ailenizin yeni güçlü dostu.',
      imageUrls: [
        'https://images.unsplash.com/photo-1551826152-d7dc5f674b24?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: true,
      viewCount: 89,
      sellerId: 'u17',
      sellerName: 'Görkem Aslan',
      sellerPhone: '+90 551 333 4444',
      sellerWhatsApp: '+90 551 333 4444',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=45',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'n3',
      title: 'Fiat Egea 1.6 Multijet',
      brand: 'Fiat',
      series: 'Egea',
      model: '1.6 Multijet',
      year: 2019,
      mileage: 88000,
      priceInTL: 650000,
      fuelType: 'Dizel',
      transmission: 'Manuel',
      bodyType: 'Sedan',
      color: 'Siyah',
      engineSize: '1.6',
      horsepower: 120,
      location: 'Mağusa',
      description: 'Yakıt ekonomisi yüksek dizel motor. İyi bakımlı, periyodik bakımları dolu.',
      imageUrls: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 67,
      sellerId: 'u18',
      sellerName: 'Oya Tekin',
      sellerPhone: '+90 553 666 7777',
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=48',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'n4',
      title: 'Skoda Octavia 2.0 TDI',
      brand: 'Skoda',
      series: 'Octavia',
      model: '2.0 TDI',
      year: 2020,
      mileage: 72000,
      priceInTL: 1080000,
      fuelType: 'Dizel',
      transmission: 'Otomatik',
      bodyType: 'Sedan',
      color: 'Yeşil',
      engineSize: '2.0',
      horsepower: 150,
      location: 'Lefkoşa',
      description: 'Style trim, Canton ses, virtual cockpit, LED matrix. Volkswagen kalitesi uygun fiyata.',
      imageUrls: [
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 134,
      sellerId: 'u19',
      sellerName: 'Berrak Yıldırım',
      sellerPhone: '+90 555 000 1234',
      sellerWhatsApp: '+90 555 000 1234',
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=50',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'n5',
      title: 'Peugeot 3008 1.2 PureTech',
      brand: 'Peugeot',
      series: '3008',
      model: '1.2 PureTech',
      year: 2021,
      mileage: 49000,
      priceInTL: 1320000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Gri',
      engineSize: '1.2',
      horsepower: 130,
      location: 'Girne',
      description: 'GT Line, i-Cockpit, FOCAL ses, ısıtmalı koltuk. Fransız tasarımının şıklığı.',
      imageUrls: [
        'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: true,
      viewCount: 203,
      sellerId: 'u20',
      sellerName: 'Cenk Güneş',
      sellerPhone: '+90 557 888 9012',
      createdAt: DateTime.now().subtract(const Duration(days: 22)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=52',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'n6',
      title: 'Seat León 2.0 TDI FR',
      brand: 'Seat',
      series: 'León',
      model: '2.0 TDI FR',
      year: 2019,
      mileage: 83000,
      priceInTL: 890000,
      fuelType: 'Dizel',
      transmission: 'Manuel',
      bodyType: 'Hatchback',
      color: 'Lacivert',
      engineSize: '2.0',
      horsepower: 150,
      location: 'Mağusa',
      description: 'FR spor paket, kupa direksiyon, Sport mod, LED ön far. Dizel sürüş tutkunları için.',
      imageUrls: [
        'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: true,
      isFavorited: false,
      viewCount: 78,
      sellerId: 'u21',
      sellerName: 'İrem Altın',
      sellerPhone: '+90 559 222 3456',
      sellerWhatsApp: '+90 559 222 3456',
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=55',
      isSellerFounderMember: false,
    ),
    ListingModel(
      id: 'n7',
      title: 'Volvo XC40 T5 AWD',
      brand: 'Volvo',
      series: 'XC40',
      model: 'T5 AWD',
      year: 2020,
      mileage: 57000,
      priceInTL: 1950000,
      fuelType: 'Benzin',
      transmission: 'Otomatik',
      bodyType: 'SUV',
      color: 'Mavi',
      engineSize: '2.0',
      horsepower: 247,
      location: 'Lefkoşa',
      description: 'R-Design, Harman Kardon, pilot assist, kablosuz şarj. İsveç güvenliğinin özeti.',
      imageUrls: [
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
      ],
      type: ListingType.normal,
      status: ListingStatus.active,
      isNegotiable: false,
      isFavorited: false,
      viewCount: 167,
      sellerId: 'u22',
      sellerName: 'Barış Çelik',
      sellerPhone: '+90 561 444 5678',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      sellerAvatarUrl: 'https://i.pravatar.cc/150?img=57',
      isSellerFounderMember: false,
    ),
  ];

  static List<ListingModel> get boostedListings =>
      listings.where((l) => l.type == ListingType.boost).toList();

  static List<ListingModel> get emergencyListings =>
      listings.where((l) => l.type == ListingType.emergency).toList();

  static List<ListingModel> get normalListings =>
      listings.where((l) => l.type == ListingType.normal).toList();

  static List<ListingModel> get favoritedListings =>
      listings.where((l) => l.isFavorited).toList();

  static UserModel get currentUser => const UserModel(
    id: 'current_user',
    name: 'Ahmet Yılmaz',
    email: 'ahmet@example.com',
    phone: '+90 555 999 0000',
    avatarUrl: 'https://i.pravatar.cc/150?img=60',
    isFounderMember: true,
    memberSince: '2024',
    totalListings: 3,
    activeListings: 2,
  );

  static final List<NotificationModel> notifications = [
    const NotificationModel(
      id: 'notif1',
      title: 'İlanınız favorilendi!',
      body: 'BMW 5 Serisi ilanınız bir kullanıcı tarafından favorilere eklendi.',
      type: NotificationType.favorited,
      isRead: false,
      createdAt: '2 saat önce',
    ),
    const NotificationModel(
      id: 'notif2',
      title: 'Boost sıranız geldi!',
      body: 'Honda CR-V ilanınız artık boost sıranda. Ödemenizi yapabilirsiniz.',
      type: NotificationType.boostReady,
      isRead: false,
      createdAt: '5 saat önce',
    ),
    const NotificationModel(
      id: 'notif3',
      title: 'İlan yenileme hatırlatması',
      body: 'Toyota Corolla ilanınızın süresi 15 gün içinde dolacak. Şimdi yenileyin.',
      type: NotificationType.renewal,
      isRead: true,
      createdAt: '1 gün önce',
    ),
    const NotificationModel(
      id: 'notif4',
      title: 'İlanınız onaylandı',
      body: 'Nissan Qashqai ilanınız admin tarafından onaylandı ve yayına alındı.',
      type: NotificationType.approved,
      isRead: true,
      createdAt: '3 gün önce',
    ),
    const NotificationModel(
      id: 'notif5',
      title: 'İlanınız favorilendi!',
      body: 'Fiat Egea ilanınız bir kullanıcı tarafından favorilere eklendi.',
      type: NotificationType.favorited,
      isRead: true,
      createdAt: '5 gün önce',
    ),
  ];

  static const List<String> brands = [
    'Alfa Romeo', 'Audi', 'BMW', 'Citroen', 'Dacia', 'Fiat', 'Ford',
    'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus',
    'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan', 'Opel',
    'Peugeot', 'Porsche', 'Renault', 'Seat', 'Skoda', 'Subaru',
    'Tesla', 'Toyota', 'Volkswagen', 'Volvo',
  ];

  static const Map<String, List<String>> brandSeries = {
    'BMW': ['1 Serisi', '2 Serisi', '3 Serisi', '4 Serisi', '5 Serisi', '7 Serisi', 'X1', 'X3', 'X5', 'M3', 'M5'],
    'Mercedes-Benz': ['A Serisi', 'B Serisi', 'C Serisi', 'E Serisi', 'S Serisi', 'GLA', 'GLC', 'GLE', 'AMG GT'],
    'Audi': ['A3', 'A4', 'A5', 'A6', 'Q3', 'Q5', 'Q7', 'TT', 'R8'],
    'Volkswagen': ['Golf', 'Passat', 'Tiguan', 'Polo', 'Touareg', 'Arteon', 'T-Roc'],
    'Toyota': ['Corolla', 'Camry', 'RAV4', 'Yaris', 'C-HR', 'Land Cruiser', 'Hilux'],
    'Ford': ['Focus', 'Fiesta', 'Kuga', 'Mustang', 'Puma', 'Edge'],
    'Honda': ['Civic', 'CR-V', 'HR-V', 'Jazz', 'Accord'],
    'Hyundai': ['i20', 'i30', 'Tucson', 'Santa Fe', 'IONIQ'],
    'Kia': ['Sportage', 'Ceed', 'Sorento', 'Stinger', 'EV6'],
    'Renault': ['Clio', 'Megane', 'Kadjar', 'Captur', 'Zoe'],
    'Dacia': ['Sandero', 'Duster', 'Logan', 'Spring'],
    'Opel': ['Corsa', 'Astra', 'Mokka', 'Crossland', 'Insignia'],
    'Fiat': ['Egea', '500', 'Tipo', 'Doblo', 'Panda'],
    'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X'],
    'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
    'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'V60', 'S90'],
    'Land Rover': ['Discovery Sport', 'Discovery', 'Range Rover', 'Defender', 'Freelander'],
    'Peugeot': ['208', '308', '508', '2008', '3008', '5008'],
    'Seat': ['León', 'Ibiza', 'Arona', 'Ateca', 'Tarraco'],
    'Skoda': ['Octavia', 'Fabia', 'Superb', 'Karoq', 'Kodiaq'],
    'Nissan': ['Qashqai', 'Juke', 'X-Trail', 'Leaf', 'Micra'],
    'Mazda': ['3', '6', 'CX-3', 'CX-5', 'CX-30', 'MX-5'],
  };

  static const List<String> locations = [
    'Lefkoşa', 'Girne', 'Mağusa', 'Güzelyurt', 'İskele', 'Lefke',
  ];

  static const List<String> fuelTypes = [
    'Benzin', 'Dizel', 'Hibrit', 'Elektrik', 'LPG', 'Benzin & LPG',
  ];

  static const List<String> transmissions = [
    'Otomatik', 'Manuel', 'Yarı Otomatik',
  ];

  static const List<String> bodyTypes = [
    'Sedan', 'Hatchback', 'SUV', 'Coupe', 'Cabrio', 'Pickup', 'Van', 'Station Wagon',
  ];

  static const List<String> colors = [
    'Siyah', 'Beyaz', 'Gümüş', 'Gri', 'Kırmızı', 'Mavi', 'Yeşil',
    'Sarı', 'Turuncu', 'Kahverengi', 'Lacivert', 'Bordo',
  ];
}
